DROP TABLE IF EXISTS REVIEWS;

CREATE TABLE REVIEWS(
ID INT NOT NULL AUTO_INCREMENT,
NAME_ID INT NOT NULL,
MOVIE_ID INT NOT NULL,
REVIEW INT,

PRIMARY KEY(ID), 
FOREIGN KEY(MOVIE_ID) REFERENCES MOVIES(ID)
);

ALTER TABLE REVIEWS
ADD CONSTRAINT FOREIGN KEY(NAME_ID) 
REFERENCES PERSON(ID)
