DROP TABLE IF EXISTS MOVIES;

CREATE TABLE MOVIES
(
	ID INT NOT NULL AUTO_INCREMENT,
	MOVIE_TITLE VARCHAR(100),
    GENRE_ID INT,
    YEAR VARCHAR(4),
    PRIMARY KEY(ID),
	FOREIGN KEY(GENRE_ID) 
		REFERENCES GENRE(ID)
		ON DELETE CASCADE
    );

    
    SELECT * FROM MOVIES;
    
   
INSERT INTO `movies`.`MOVIES` (`ID`, `MOVIE_TITLE`, `GENRE_ID`, `YEAR`) VALUES ('1', 'Thor: Love and Thunder', '1', '2022');
INSERT INTO `movies`.`MOVIES` (`ID`, `MOVIE_TITLE`, `GENRE_ID`, `YEAR`) VALUES ('2', 'PINOCCHIO', '6', '2022');
INSERT INTO `movies`.`MOVIES` (`ID`, `MOVIE_TITLE`, `GENRE_ID`, `YEAR`) VALUES ('3', 'BEAST', '2', '2022');
INSERT INTO `movies`.`MOVIES` (`ID`, `MOVIE_TITLE`, `GENRE_ID`, `YEAR`) VALUES ('4', 'SAMARITAN', '1', '2022');
INSERT INTO `movies`.`MOVIES` (`ID`, `MOVIE_TITLE`, `GENRE_ID`, `YEAR`) VALUES ('5', 'ME-TIME', '7', '2022');
INSERT INTO `movies`.`MOVIES` (`ID`, `MOVIE_TITLE`, `GENRE_ID`, `YEAR`) VALUES ('6', 'Fullmetal Alchemist the Revenge of Scar', '2', '2022');


  SELECT * FROM MOVIES;