DROP TABLE IF EXISTS PERSON;

CREATE TABLE PERSON(
ID INT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(50) NOT NULL,

PRIMARY KEY(ID)
);


INSERT INTO `movies`.`PERSON` (`ID`, `NAME`) VALUES ('1', 'JOHN');
INSERT INTO `movies`.`PERSON` (`ID`, `NAME`) VALUES ('2', 'ANGELICA');
INSERT INTO `movies`.`PERSON` (`ID`, `NAME`) VALUES ('3', 'JUAN');
INSERT INTO `movies`.`PERSON` (`ID`, `NAME`) VALUES ('4', 'CHRIS');
INSERT INTO `movies`.`PERSON` (`ID`, `NAME`) VALUES ('5', 'DANA');