---
title: "data607_project1"
author: "karmaGyatso"
date: '2022-09-25'
output:
  html_document: default
  pdf_document: default
---

```{r}
library(tidyverse)
library(knitr)
library(stringr)
library(tidyr)
```


```{r}
chess_data <- read.delim("https://raw.githubusercontent.com/karmaggyatso/CUNY_SPS/main/Github_data607/project1/tournamentinfo.txt", header = FALSE, stringsAsFactors = FALSE)

head(chess_data, n = 80)
```

```{r}
split_data <- data.frame(str_replace_all(chess_data$V1,"-",""))
head(split_data)
```

```{r}
split_data <- data.frame(split_data[!apply(split_data == "", 1, all),])
head(split_data)
```
```{r}
temp_table <- data.frame(c())

for (i in 1:dim(split_data)[1]){
  if (i %% 2 == 1) {
    Part1 <- rbind(temp_table$Part1, as.character(split_data[i,1]))
    Part2 <- as.character(split_data[i+1,1])
    Combined <- data.frame(paste0(Part1, Part2))
    names(Combined) <- "Combined"
    temp_table <- rbind(temp_table, Combined)
  } 
}

head(temp_table)
```

```{r}
Headers <- c("Pair","Player Name","Total","Round 1","Round 2","Round 3", "Round 4","Round 5","Round 6","Round 7","State","USCF ID / Rtg (Pre->Post)","Pts","1","2","3","4","5","6","7","Ave Pre Rating")

newer_table <- separate(data = temp_table, col = Combined, into = Headers, sep = "\\|")
# Need to clear row containing all columns names
newer_table <- newer_table[-c(1), ]

head(newer_table)
```
```{r}
temp <- str_extract_all(newer_table$`USCF ID / Rtg (Pre->Post)`,"\\b\\d{1,}")
temp <- data.frame(as.character(temp))
# Separating the data frame from one couln to three different columns
temp <- separate(data = temp, col = as.character.temp., into = c("col1","col2","col3"), sep = ",")
kable(head(temp))
temp$col1
```

```{r}
col1 <- str_extract_all(temp$col1,"[[:digit:]]{1,}")
col2 <- str_extract_all(temp$col2,"[[:digit:]]{1,}")
col3 <- str_extract_all(temp$col3,"[[:digit:]]{1,}")


newer_table$`USCF ID` <- as.character(col1)
newer_table$`Pre Rating` <- as.character(col2)
newer_table$`Post Rating` <- as.character(col3)
head(newer_table)
```
```{r}
csv.table <- subset(newer_table, select = c(1,2,3,4,5,6,7,8,9,10, 11, 21, 22, 23,24, 13, 14))
kable(head(csv.table))
kable(csv.table, row.names = FALSE)
write.table(csv.table, file = "project1-chessTournamentInfo.csv",row.names=FALSE, na="",col.names=TRUE, sep=",")
```

